# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fd691a581acd771d27c4fce85904629f79db35aa7f3a1c8570f6b0aac68c4c73d5a355793ac2ade993f105eac74ecc1b80613b57a8a0df784d666338f31557a

test:
  secret_key_base: c526e00512a393cc0119d4e74cb6f80ef534944b8f3821bf91096f17ad88b0be0599160b87cc84c700232f395e202889aaff0a3d6aa3cd3bcd46ba550ccb4f40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
